services:
  hackernews-salvo:
    image: ubuntu:latest
    container_name: "hackernews-salvo"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
    entrypoint: "chmod +x /site/hackernews-salvo && /site/hackernews-salvo"
    ports:
      - 8000:8000
    volumes:
      - "/target/site:/site"
      - "/target/server/release/hackernews-salvo:/site/hackernews-salvo"