services:
  hackernews-salvo:
    build: './'
    # context: .
    container_name: "hackernews-salvo"
    # restart: always
    # working_dir: "/target"
    entrypoint: /bin/bash
    command: -c "chmod +x hackernews-salvo && ./hackernews-salvo"
    ports:
      - 8000:8000
    environment:
      GLORY_SITE_ADDR: "0.0.0.0:8000"
    volumes:
      - "./target:/target"
      # - "./public:/site/public"
      # - "./Cargo.toml:/site/Cargo.toml"
      - "./target/server/release/hackernews-salvo:/hackernews-salvo"